version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-patch" ]
    commit-message:
      prefix: "mvn"
#    reviewers:
#      - "apache/beam"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
