  name: "validate yaml pipeline"
  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
  jobs:
    test:
        name: validate pipeline
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
            with:
              fetch-depth: 0
          - name: Set up JDK 11
            uses: actions/setup-java@v1
            with:
              java-version: '11'
              distribution: 'temurin'
          - name: Build with Maven
            run: mvn -B package --file pom.xml
          - name: Set up python
            uses: actions/setup-python@v5
            with:
              python-version: '3.12'
          - name: Set up Apache Beam Yaml
            run: pip install apache_beam[yaml,gcp]
          - name: Test Yaml pipeline
            run: |
              python -m apache_beam.yaml.main --yaml_pipeline_file=test-pipeline.yaml &> logfile
              if [ $(grep -o 'JOHN' logfile | wc -l) -eq 1 ];
              then
                exit 0
              else
               exit 1
              fi
